// Comprehensive list of design inspiration sources from:
// - Brian Lovin's curated sites (brianlovin.com/sites)
// - InspofFeed (inspofeed.com)

export const brianLovinSites = [
  { name: 'Good Aesthetic', url: 'goodaesthetic.club', category: 'Gallery' },
  { name: 'Ryhan Hassan', url: 'ryhan.me', category: 'Portfolio' },
  { name: 'LogSnag', url: 'logsnag.com', category: 'SaaS' },
  { name: 'Brandon Walkin', url: 'brandonwalkin.com', category: 'Portfolio' },
  { name: 'Daniel Destefanis', url: 'danield.design', category: 'Designer' },
  { name: 'Jeff Smith', url: 'jeffsmith.design', category: 'Designer' },
  { name: 'Julian Lehr', url: 'julian.digital', category: 'Digital' },
  { name: 'Chase McCoy', url: 'chsmc.org', category: 'Portfolio' },
  { name: 'Tom Petty', url: 'tom.pe', category: 'Personal' },
  { name: 'Jean-Marc Denis', url: 'jmd.im', category: 'Portfolio' },
  { name: 'Claudio Guglieri', url: 'guglieri.com', category: 'Designer' },
  { name: 'Jin Su Park', url: 'jinsupark.com', category: 'Portfolio' },
  { name: 'Wireframe', url: 'wireframe.co', category: 'Agency' },
  { name: 'Nick Jones', url: 'narrowdesign.com', category: 'Designer' },
  { name: 'Michael Villar', url: 'michaelvillar.com', category: 'Interactions' },
  { name: 'Edwin Morris', url: 'ehmorris.com', category: 'Designer' },
  { name: 'Design Engineer', url: 'designengineer.io', category: 'Community' },
  { name: 'William Bout', url: 'williambout.me', category: 'Portfolio' },
  { name: 'Lingxi Li', url: 'lingxi.li/blog', category: 'Blog' },
  { name: 'Joseph Zhang', url: 'joseph.cv', category: 'Portfolio' },
  { name: 'Paul Stamatiou', url: 'paulstamatiou.com', category: 'Designer' },
  { name: 'Jonnie Hallman', url: 'destroytoday.com', category: 'Designer' },
  { name: 'Mackenzie Child', url: 'mackenziechild.me', category: 'Portfolio' },
  { name: 'Rauno Freiberg', url: 'rauno.me', category: 'Designer' },
  { name: 'Matt Rothenberg', url: 'mattrothenberg.com', category: 'Designer' },
  { name: 'Alexey Sekachov', url: 'asekachov.com', category: 'Designer' },
  { name: 'Frank Costa', url: 'okfrank.co', category: 'Designer' },
  { name: 'Paco Coursey', url: 'paco.me', category: 'Portfolio' },
  { name: 'Amie', url: 'amie.so', category: 'SaaS' },
  { name: 'Simone Magurno', url: 'magur.no', category: 'Designer' },
  { name: 'Joi Planner', url: 'joi.software', category: 'Software' },
  { name: 'Fabrizio Rinaldi', url: 'fabrizio.so', category: 'Designer' },
  { name: 'Krijn Rijshouwer', url: 'krijnrijshouwer.com', category: 'Designer' },
  { name: 'Mark Hurrell', url: 'mhurrell.co.uk', category: 'Designer' },
  { name: 'Charlie Deets', url: 'charliedeets.com', category: 'Designer' },
  { name: 'Niki Tonsky', url: 'tonsky.me', category: 'Blog' },
  { name: 'Rafael Conde', url: 'rafa.design', category: 'Designer' },
  { name: 'Justin Windle', url: 'soulwire.co.uk', category: 'Generative' },
  { name: 'Yann-Edern Gillet', url: 'yannglt.com', category: 'Designer' },
  { name: 'Danny Jones', url: 'yasly.com', category: 'Designer' },
  { name: 'Neal Agarwal', url: 'neal.fun', category: 'Fun' },
  { name: 'Sunday', url: 'sunday.ai', category: 'AI' },
  { name: 'Making Software', url: 'makingsoftware.com', category: 'Book' },
  { name: 'Amelia Wattenberger', url: 'wattenberger.com', category: 'Designer' },
  { name: 'Carl Barenbrug', url: 'carlbarenbrug.com', category: 'Designer' },
  { name: 'Adrián Mato', url: 'adrianmato.com', category: 'Designer' },
  { name: 'Fine Thought', url: 'finethought.com.au', category: 'Studio' },
  { name: 'Steven Sarmiento', url: 'stevensarmi.com', category: 'Designer' },
  { name: 'Jeff Anders', url: 'jhil.co', category: 'Designer' },
  { name: 'Void Notepad', url: 'voidnotepad.com', category: 'Tool' },
  { name: 'Alex Cornell', url: 'alexcornell.com', category: 'Designer' },
  { name: 'Tobias Ahlin', url: 'tobiasahlin.com', category: 'Designer' },
  { name: 'Cursor', url: 'cursor.com', category: 'IDE' },
  { name: 'Philip Davis', url: 'philipcdavis.com/experiments', category: 'Experiments' },
  { name: 'Marco', url: 'marco.fyi', category: 'Designer' },
  { name: 'Allan Grinshtein', url: 'allan.bio', category: 'Designer' },
  { name: 'SF Computer', url: 'sfcompute.com', category: 'Company' },
  { name: 'Stripe Press', url: 'press.stripe.com', category: 'Media' },
  { name: 'Kevin Clark', url: 'kevinclark.ca', category: 'Designer' },
  { name: 'Jasper Hauser', url: 'jasperhauser.nl', category: 'Designer' },
  { name: 'Shu Ding', url: 'shud.in', category: 'Designer' },
  { name: 'Steve Hayes', url: 'stevehay.es', category: 'Designer' },
  { name: 'Marc Bouchenoire', url: 'marcbouchenoire.com', category: 'Designer' },
  { name: 'Maxime Heckel', url: 'maximeheckel.com', category: 'Designer' },
  { name: 'Josh W. Comeau', url: 'joshwcomeau.com', category: 'Designer' },
  { name: 'Chris Welch', url: 'chriswelch.co', category: 'Designer' },
  { name: 'Tom Johnson', url: 'tomjohn.design', category: 'Designer' },
  { name: 'Gabriel Valdivia', url: 'gabrielvaldivia.com', category: 'Designer' },
  { name: 'Robert Pavlinić', url: 'rpavlini.com', category: 'Designer' },
  { name: 'Rasmus Andersson', url: 'rsms.me', category: 'Designer' },
  { name: 'Interactions', url: 'khagwal.com/interactions', category: 'Gallery' },
  { name: 'Poolside', url: 'poolside.ai', category: 'AI' },
  { name: 'Amanda Pinsker', url: 'amandapinsker.com', category: 'Designer' },
  { name: 'Petter Nilsson', url: 'petter.pro', category: 'Designer' },
  { name: 'Daniel Eden', url: 'daneden.me', category: 'Designer' },
  { name: 'Marijana Pavlinić', url: 'marijanapav.com', category: 'Designer' },
  { name: 'Ryo Lu', url: 'ryo.lu', category: 'Designer' },
  { name: 'Andy Matuschak Notes', url: 'notes.andymatuschak.org', category: 'Learning' },
  { name: 'Adam Whitcroft', url: 'adamwhitcroft.com', category: 'Designer' },
  { name: 'Jon Rothenberg', url: 'designbyjon.com', category: 'Designer' },
  { name: 'Ben Issen', url: 'benissen.com/projects/side-school', category: 'Learning' },
];

export const inspofeedLinks = [
  { name: 'ARK Studio', url: 'ark.studio', category: 'Studio' },
  { name: 'ALW Design', url: 'alw.design', category: 'Design' },
  { name: 'ECAL', url: 'ecal.ch', category: 'School' },
  { name: 'Form', url: 'form.co.uk', category: 'Studio' },
  { name: 'Vast', url: 'vast.com', category: 'Platform' },
  { name: 'Gal Shir', url: 'galshir.com', category: 'Designer' },
  { name: 'Wemake Studio', url: 'wemakestudio.com', category: 'Studio' },
  { name: 'Ogilvy', url: 'ogilvy.com', category: 'Agency' },
  { name: 'Humaan', url: 'humaan.com', category: 'Agency' },
  { name: 'Otherworldly', url: 'otherworldly.com', category: 'Studio' },
  { name: 'One & Co', url: 'oneandco.com', category: 'Studio' },
  { name: 'ISO Reponsiv', url: 'iso.rep.com', category: 'Agency' },
  { name: 'Brutalist Websites', url: 'brutalistwebsites.com', category: 'Gallery' },
  { name: 'Design Museum', url: 'designmuseum.org', category: 'Museum' },
  { name: 'Base Designs', url: 'basedesigns.co', category: 'Studio' },
  { name: 'Solid Studio', url: 'solidstudio.co', category: 'Studio' },
  { name: 'Made Thought', url: 'madethought.com', category: 'Studio' },
  { name: 'TwentyTwo', url: 'twentytwostudio.com', category: 'Studio' },
  { name: 'Landor', url: 'landor.com', category: 'Agency' },
  { name: 'Peter Halley', url: 'peterhalley.com', category: 'Artist' },
];

export const inspirationCategories = {
  Portfolio: 'Personal portfolios and CV sites',
  Designer: 'Individual designer sites',
  Studio: 'Design studios and collectives',
  Agency: 'Design agencies',
  SaaS: 'Software as a Service products',
  Tool: 'Web-based tools and utilities',
  Gallery: 'Design galleries and showcases',
  Blog: 'Design blogs and writing',
  Interactions: 'Animation and interaction examples',
  Community: 'Design communities',
  Learning: 'Learning resources',
  Generative: 'Generative and creative coding',
  AI: 'AI-powered platforms',
  Personal: 'Personal projects',
  Digital: 'Digital products',
  Experiments: 'Experimental projects',
  Fun: 'Fun and playful sites',
  Book: 'Books and publications',
  Media: 'Media and editorial',
  Company: 'Company websites',
  IDE: 'Development tools',
  School: 'Educational institutions',
  Platform: 'Platforms and services',
  Artist: 'Artist websites',
  Museum: 'Museums and cultural institutions',
};

// Grouped by learning focus
export const inspirationByCategory = {
  typeface: [
    'tobiasahlin.com',
    'niki.tonsky.me',
    'tonsky.me',
    'joshwcomeau.com',
  ],
  interaction: [
    'rauno.me',
    'daneden.me',
    'khagwal.com/interactions',
    'soulwire.co.uk',
    'michaelvillar.com',
  ],
  colorSystem: [
    'goodaesthetic.club',
    'paco.me',
    'magur.no',
    'rafa.design',
  ],
  layout: [
    'paulstamatiou.com',
    'wattenberger.com',
    'maximeheckel.com',
    'rsms.me',
  ],
  performance: [
    'shud.in',
    'peterhalley.com',
    'kevinclark.ca',
  ],
  accessibility: [
    'joshwcomeau.com',
    'wattenberger.com',
    'tonsky.me',
  ],
  animation: [
    'daneden.me',
    'tobiasahlin.com',
    'rauno.me',
  ],
  designSystems: [
    'cursor.com',
    'amie.so',
    'joi.software',
  ],
};

export type InspirationSource = typeof brianLovinSites[0];
